version: '3.8'

services:
  anyflow_postgres:
    image: postgres:latest
    container_name: anyflow_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql2/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "9090:80"
  # app:
  #   build:
  #     context: .
  #   container_name: laravel_app
  #   environment:
  #     DB_CONNECTION: ${DB_CONNECTION}
  #     DB_HOST: postgres
  #     DB_PORT: ${DB_PORT}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
  postgres_data:
